# Generated by Django 3.2.3 on 2021-06-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_rename_email_reg_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='Email_id',
            new_name='email',
        ),
    ]
