# Generated by Django 3.2.3 on 2021-06-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_reserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reserve',
        ),
    ]
