# Generated by Django 3.2.3 on 2021-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('activation', models.CharField(max_length=100)),
            ],
        ),
    ]
