# Generated by Django 3.2.3 on 2021-06-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='datefrom',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='dateto',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='equip',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='returns',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.CharField(max_length=1000),
        ),
    ]
