# Generated by Django 3.2.3 on 2021-06-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_auto_20210607_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.CharField(default=23, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=33, max_length=1000),
            preserve_default=False,
        ),
    ]
