# Generated by Django 3.2.3 on 2021-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0015_auto_20210607_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=1000)),
                ('payment', models.CharField(max_length=1000)),
                ('count', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
            ],
        ),
    ]
