# Generated by Django 3.2.3 on 2021-06-12 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0017_auto_20210611_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
